name: Build & Release EXE

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_dispatch:


permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
      
      - name: Build EXE
        run: |
          pyinstaller --noconsole --onefile --name "Syntiox-DL" --icon "assets/icon.ico" --collect-all customtkinter --add-data "core;core" --add-data "assets;assets" main.py

      - name: Build Installer (Inno Setup)
        run: |
          & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" installer.iss

      - name: Upload EXE to Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_type == 'tag' && github.ref_name || 'latest' }}
          name: "🚀 Syntiox DL - ${{ github.ref_type == 'tag' && github.ref_name || 'Latest Release' }}"
          body: |
            ## 🌟 What's New in this Build!
            This is the latest auto-generated build of Syntiox DL.
            
            📝 **Latest Changes:**
            ```text
            ${{ github.event.head_commit.message }}
            ```
            
            ---
            *👇 Download `Syntiox DL.exe` below to install or update your app!*
          files: 'dist/Syntiox DL.exe'
